steps:
  - name: gcr.io/cloud-builders/docker
    id: Build image
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_IMAGE_TAG}
      - --build-arg
      - VITE_API_BASE_URL=${_VITE_API_BASE_URL}
      - --build-arg
      - VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}
      - --build-arg
      - VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}
      - --build-arg
      - VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}
      - --build-arg
      - VITE_FIREBASE_STORAGE_BUCKET=${_VITE_FIREBASE_STORAGE_BUCKET}
      - --build-arg
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${_VITE_FIREBASE_MESSAGING_SENDER_ID}
      - --build-arg
      - VITE_FIREBASE_APP_ID=${_VITE_FIREBASE_APP_ID}
      - --build-arg
      - VITE_GOOGLE_MAPS_API_KEY=${_VITE_GOOGLE_MAPS_API_KEY}
      - .

  - name: gcr.io/cloud-builders/docker
    id: Push image
    args:
      - push
      - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_IMAGE_TAG}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy Cloud Run
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_IMAGE_TAG}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-env-vars
      - CORS_ALLOW_ORIGINS=${_CORS_ALLOW_ORIGINS},GCP_PROJECT_ID=$PROJECT_ID,GCP_LOCATION=${_GCP_LOCATION},GOOGLE_MAPS_API_KEY=${_SERVER_GOOGLE_MAPS_API_KEY}

images:
  - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_IMAGE_TAG}

substitutions:
  _SERVICE_NAME: triplo
  _IMAGE_TAG: latest
  _REGION: asia-northeast3
  _GCP_LOCATION: asia-northeast3
  _VITE_API_BASE_URL: /api
  _CORS_ALLOW_ORIGINS: "*"
